/**
 * Emit a service worker that precaches exactly what this build produced.
 *
 * A hand-written sw.js cannot list Vite's output, because the filenames carry content
 * hashes that only exist after the bundle is written. So the list is injected here, and
 * the cache name is derived from it — which means adding or changing any asset
 * automatically invalidates the old cache instead of leaving a stale one behind.
 *
 * Written rather than copied: no lab in this fleet ships a service worker, and the one
 * hand-written service worker in the wider repository set serves a site at a domain root
 * and uses root-absolute paths, which 404 under a GitHub Pages project subpath.
 */

import type { Plugin } from 'vite';

function shortHash(input: string): string {
  // FNV-1a. Not a security primitive — it only has to change when the asset list changes.
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

export function offlinePlugin(base: string): Plugin {
  let assets: string[] = [];
  return {
    name: 'token-tell-offline',
    apply: 'build',
    generateBundle(_options, bundle) {
      assets = Object.keys(bundle)
        .filter((name) => !name.endsWith('.map'))
        .map((name) => `${base}${name}`)
        .sort();
    },
    closeBundle: {
      sequential: true,
      async handler() {
        const { writeFile } = await import('node:fs/promises');
        const { join } = await import('node:path');
        const core = [base, ...assets, `${base}manifest.webmanifest`];
        const version = `token-tell-${shortHash(core.join('|'))}`;
        const source = `/* Generated by tools/vite-plugin-offline.ts at build time.
 * Precaches exactly the assets this build emitted, under this deployment's base path.
 * The cache name is derived from that list, so a changed asset retires the old cache.
 */
'use strict';

const VERSION = ${JSON.stringify(version)};
const BASE = ${JSON.stringify(base)};
const CORE = ${JSON.stringify(core, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(VERSION).then((cache) => cache.addAll(CORE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((name) => name !== VERSION).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network so a deploy is picked up, fall back to the cached shell
  // so the lab keeps working with no connection at all.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match(BASE).then((cached) => cached ?? Response.error())),
    );
    return;
  }

  // Everything else is content-hashed, so a cache hit is always the right answer.
  event.respondWith(
    caches.match(request).then((cached) => cached ?? fetch(request).then((response) => {
      if (response.ok) {
        const copy = response.clone();
        void caches.open(VERSION).then((cache) => cache.put(request, copy));
      }
      return response;
    })),
  );
});
`;
        await writeFile(join(process.cwd(), 'dist', 'sw.js'), source, 'utf8');
      },
    },
  };
}
